### 회원 가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
"name":"이종혁"
,"email":"jh2@kakao.com"
,"password":"1234"
}


### 로그인 요청 테스트
POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=jh2@kakao.com&password=1234&remember=1
