
### 게시글 작성 테스트 요청

POST http://localhost:8080/posts
Content-Type: application/json

{
  "title" : "제목",
  "content" : "내용"
}

### 게시글 삭제 테스트 요청

DELETE http://localhost:8080/posts/2
Content-Type: application/json
